# Generated by Django 6.0.6 on 2026-06-22 14:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_rollnumber', models.IntegerField(unique=True)),
                ('stu_name', models.CharField(max_length=40)),
                ('stu_class', models.CharField(max_length=6)),
                ('stu_gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('others', 'OTHERS')], max_length=11)),
                ('stu_mobile', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('[6-9][0-9]{9}')])),
                ('stu_image', models.ImageField(upload_to='images/')),
                ('stu_markssheet', models.FileField(upload_to='files/')),
            ],
        ),
    ]
