# Generated by Django 6.0.6 on 2026-06-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_address_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('success', 'Success'), ('failure', 'Failure')], default='pending', max_length=15),
        ),
    ]
