# Generated by Django 6.0.6 on 2026-06-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('upi', 'upi'), ('cod', 'cod')], max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('verified', 'verified'), ('success', 'success'), ('failure', 'failure')], default='pending', max_length=15),
        ),
    ]
